apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: todo
  annotations:
    # If using MetalLB, you can set specific annotations here
    # metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
