apiVersion: v1
kind: Namespace
metadata:
  name: todo
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: todo
type: Opaque
stringData:
  # Postgres credentials and database name
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "todo_db"
  # Backend pg client envs (reuse same values)
  PGUSER: "postgres"
  PGPASSWORD: "postgres"
  PGDATABASE: "todo_db"
