apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: todo
spec:
  selector:
    app: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todo
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todo
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
